// Source: github.com/mahfuzarrahmanmunna/bd-divission-dirtrict-thanas
export const BD_GEO = {
  "Bagerhat": [
    "Bagerhat Sadar",
    "Chitalmari",
    "Fakirhat",
    "Kachua",
    "Mollahat",
    "Mongla",
    "Morrelganj",
    "Rampal",
    "Sarankhola",
  ],
  "Bandarban": [
    "Ali kadam",
    "Bandarban Sadar",
    "Lama",
    "Naikhongchhari",
    "Rowangchhari",
    "Ruma",
    "Thanchi",
  ],
  "Barguna": [
    "Amtali",
    "Bamna",
    "Barguna Sadar",
    "Betagi",
    "Patharghata",
    "Taltali",
  ],
  "Barisal": [
    "Agailjhara",
    "Babuganj",
    "Bakerganj",
    "Banaripara",
    "Barisal Sadar",
    "Gaurnadi",
    "Hizla",
    "Mehendiganj",
    "Muladi",
    "Wazirpur",
  ],
  "Bhola": [
    "Bhola Sadar",
    "Burhanuddin",
    "Char Fasson",
    "Daulatkhan",
    "Lalmohan",
    "Manpura",
    "Tazumuddin",
  ],
  "Bogra": [
    "Adamdighi",
    "Bogra Sadar",
    "Dhunat",
    "Dhupchanchia",
    "Gabtali",
    "Kahaloo",
    "Nandigram",
    "Sariakandi",
    "Shajahanpur",
    "Sherpur",
    "Shibganj",
    "Sonatola",
  ],
  "Brahmanbaria": [
    "Akhaura",
    "Ashuganj",
    "Bancharampur",
    "Bijoynagar",
    "Brahmanbaria Sadar",
    "Kasba",
    "Nabinagar",
    "Nasirnagar",
    "Sarail",
    "Shahbazpur",
  ],
  "Chandpur": [
    "Chandpur Sadar",
    "Faridganj",
    "Haimchar",
    "Haziganj",
    "Kachua",
    "Matlab Dakshin",
    "Matlab Uttar",
    "Shahrasti",
  ],
  "Chittagong": [
    "Anwara",
    "Banshkhali",
    "Boalkhali",
    "Chandanaish",
    "Chittagong Sadar",
    "Fatikchhari",
    "Hathazari",
    "Lohagara",
    "Mirsharai",
    "Patiya",
    "Rangunia",
    "Raozan",
    "Sandwip",
    "Satkania",
    "Sitakunda",
  ],
  "Chuadanga": [
    "Alamdanga",
    "Chuadanga Sadar",
    "Damurhuda",
    "Jibannagar",
  ],
  "Comilla": [
    "Barura",
    "Brahmanpara",
    "Burichang",
    "Chandina",
    "Chauddagram",
    "Comilla Sadar",
    "Daudkandi",
    "Debidwar",
    "Homna",
    "Laksam",
    "Meghna",
    "Monohorgonj",
    "Muradnagar",
    "Nangalkot",
    "Titas",
  ],
  "Cox's Bazar": [
    "Chakaria",
    "Cox's Bazar Sadar",
    "Kutubdia",
    "Maheshkhali",
    "Pekua",
    "Ramu",
    "Teknaf",
    "Ukhia",
  ],
  "Dhaka": [
    "Badda",
    "Biman Bandar",
    "Cantonment",
    "Dakshin Khan",
    "Demra",
    "Dhamrai",
    "Dohar",
    "Gulshan",
    "Hazaribagh",
    "Kafrul",
    "Kalabagan",
    "Keraniganj",
    "Khilgaon",
    "Kotwali",
    "Lalbagh",
    "Mirpur",
    "Mohammadpur",
    "Motijheel",
    "Nawabganj",
    "Pallabi",
    "Ramna",
    "Rampura",
    "Sabujbagh",
    "Savar",
    "Shah Ali",
    "Shahbag",
    "Sher-e-Bangla Nagar",
    "Tejgaon",
    "Turag",
    "Uttar Khan",
    "Uttara",
  ],
  "Dinajpur": [
    "Biral",
    "Birampur",
    "Birganj",
    "Bochaganj",
    "Chirirbandar",
    "Dinajpur Sadar",
    "Fulbari",
    "Ghoraghat",
    "Hakimpur",
    "Kaharole",
    "Khansama",
    "Nawabganj",
    "Parbatipur",
  ],
  "Faridpur": [
    "Alfadanga",
    "Bhanga",
    "Boalmari",
    "Charbhadrasan",
    "Faridpur Sadar",
    "Madhukhali",
    "Nagarkanda",
    "Sadarpur",
    "Saltha",
  ],
  "Feni": [
    "Chhagalnaiya",
    "Daganbhuiyan",
    "Feni Sadar",
    "Fulgazi",
    "Parshuram",
    "Sonagazi",
  ],
  "Gaibandha": [
    "Gaibandha Sadar",
    "Gobindaganj",
    "Palashbari",
    "Phulchhari",
    "Sadullapur",
    "Sughatta",
    "Sundarganj",
  ],
  "Gazipur": [
    "Gazipur Sadar",
    "Kaliakair",
    "Kaliganj",
    "Kapasia",
    "Sreepur",
  ],
  "Gopalganj": [
    "Gopalganj Sadar",
    "Kashiani",
    "Kotalipara",
    "Muksudpur",
    "Tungipara",
  ],
  "Habiganj": [
    "Ajmiriganj",
    "Bahubal",
    "Baniyachong",
    "Chunarughat",
    "Habiganj Sadar",
    "Lakhai",
    "Madhabpur",
    "Nabiganj",
  ],
  "Jamalpur": [
    "Baksiganj",
    "Dewanganj",
    "Islampur",
    "Jamalpur Sadar",
    "Madarganj",
    "Melandaha",
    "Sarishabari",
  ],
  "Jessore": [
    "Abhaynagar",
    "Bagherpara",
    "Chaugachha",
    "Jessore Sadar",
    "Jhikargachha",
    "Keshabpur",
    "Manirampur",
    "Sharsha",
  ],
  "Jhalokati": [
    "Jhalokati Sadar",
    "Kathalia",
    "Nalchity",
    "Rajapur",
  ],
  "Jhenaidah": [
    "Harinakunda",
    "Jhenaidah Sadar",
    "Kaliganj",
    "Kotchandpur",
    "Maheshpur",
    "Shailkupa",
  ],
  "Joypurhat": [
    "Akkelpur",
    "Joypurhat Sadar",
    "Kalai",
    "Khetlal",
    "Panchbibi",
  ],
  "Khagrachhari": [
    "Dighinala",
    "Guimara",
    "Khagrachhari Sadar",
    "Laxmichhari",
    "Manikchhari",
    "Matiranga",
    "Mohalchhari",
    "Panchhari",
    "Ramgarh",
  ],
  "Khulna": [
    "Batiaghata",
    "Dacope",
    "Dighalia",
    "Dumuria",
    "Khulna Sadar",
    "Koyra",
    "Paikgachha",
    "Phultala",
    "Rupsa",
    "Terokhada",
  ],
  "Kishoreganj": [
    "Austagram",
    "Bajitpur",
    "Bhairab",
    "Hossainpur",
    "Itna",
    "Karimganj",
    "Katiadi",
    "Kishoreganj Sadar",
    "Kuliarchar",
    "Mithamain",
    "Nikli",
    "Pakundia",
    "Tarail",
  ],
  "Kurigram": [
    "Bhurungamari",
    "Char Rajibpur",
    "Chilmari",
    "Kurigram Sadar",
    "Phulbari",
    "Rajarhat",
    "Raomari",
    "Ulipur",
  ],
  "Kushtia": [
    "Bheramara",
    "Daulatpur",
    "Khoksa",
    "Kumarkhali",
    "Kushtia Sadar",
    "Mirpur",
  ],
  "Lakshmipur": [
    "Kamalnagar",
    "Lakshmipur Sadar",
    "Raipur",
    "Ramganj",
    "Ramgati",
  ],
  "Lalmonirhat": [
    "Aditmari",
    "Hatibandha",
    "Kaliganj",
    "Lalmonirhat Sadar",
    "Patgram",
  ],
  "Madaripur": [
    "Kalkini",
    "Madaripur Sadar",
    "Rajoir",
    "Shibchar",
  ],
  "Magura": [
    "Magura Sadar",
    "Mohammadpur",
    "Shalikha",
    "Sreepur",
  ],
  "Manikganj": [
    "Daulatpur",
    "Ghior",
    "Harirampur",
    "Manikganj Sadar",
    "Saturia",
    "Shibaloy",
    "Singair",
  ],
  "Meherpur": [
    "Gangni",
    "Meherpur Sadar",
    "Mujibnagar",
  ],
  "Moulvibazar": [
    "Barlekha",
    "Juri",
    "Kamalganj",
    "Kulaura",
    "Moulvibazar Sadar",
    "Rajnagar",
    "Sreemangal",
  ],
  "Munshiganj": [
    "Gazaria",
    "Lohajang",
    "Munshiganj Sadar",
    "Sirajdikhan",
    "Sreenagar",
    "Tongibari",
  ],
  "Mymensingh": [
    "Bhaluka",
    "Dhobaura",
    "Fulbaria",
    "Gaffargaon",
    "Gauripur",
    "Haluaghat",
    "Ishwarganj",
    "Muktagachha",
    "Mymensingh Sadar",
    "Nandail",
    "Phulpur",
    "Trishal",
  ],
  "Naogaon": [
    "Atrai",
    "Badalgachhi",
    "Dhamoirhat",
    "Manda",
    "Mohadevpur",
    "Naogaon Sadar",
    "Niamatpur",
    "Patnitala",
    "Porsha",
    "Raninagar",
    "Sapahar",
  ],
  "Narail": [
    "Kalia",
    "Lohagara",
    "Narail Sadar",
  ],
  "Narayanganj": [
    "Araihazar",
    "Bandar",
    "Narayanganj Sadar",
    "Rupganj",
    "Sonargaon",
  ],
  "Narsingdi": [
    "Belabo",
    "Monohardi",
    "Narsingdi Sadar",
    "Palash",
    "Raipura",
    "Shibpur",
  ],
  "Natore": [
    "Bagatipara",
    "Baraigram",
    "Gurudaspur",
    "Lalpur",
    "Natore Sadar",
    "Singra",
  ],
  "Nawabganj": [
    "Bholahat",
    "Gomastapur",
    "Nachole",
    "Nawabganj Sadar",
    "Shibganj",
  ],
  "Netrokona": [
    "Atpara",
    "Barhatta",
    "Durgapur",
    "Kalmakanda",
    "Kendua",
    "Khaliajuri",
    "Madan",
    "Mohanganj",
    "Netrokona Sadar",
    "Purbadhala",
  ],
  "Nilphamari": [
    "Dimla",
    "Domar",
    "Jaldhaka",
    "Kishoreganj",
    "Nilphamari Sadar",
    "Saidpur",
  ],
  "Noakhali": [
    "Begumganj",
    "Chatkhil",
    "Companiganj",
    "Hatiya",
    "Kabirhat",
    "Noakhali Sadar",
    "Senbagh",
    "Sonaimuri",
    "Subarnachar",
  ],
  "Pabna": [
    "Atgharia",
    "Bera",
    "Bhangura",
    "Chatmohar",
    "Faridpur",
    "Ishwardi",
    "Pabna Sadar",
    "Santhia",
    "Sujanagar",
  ],
  "Panchagarh": [
    "Atwari",
    "Boda",
    "Debiganj",
    "Panchagarh Sadar",
    "Tetulia",
  ],
  "Patuakhali": [
    "Bauphal",
    "Dashmina",
    "Dumki",
    "Galachipa",
    "Kalapara",
    "Mirzaganj",
    "Patuakhali Sadar",
    "Rangabali",
  ],
  "Pirojpur": [
    "Bhandaria",
    "Kawkhali",
    "Mathbaria",
    "Nazirpur",
    "Nesarabad",
    "Pirojpur Sadar",
  ],
  "Rajbari": [
    "Baliakandi",
    "Goalandaghat",
    "Kalukhali",
    "Pangsha",
    "Rajbari Sadar",
  ],
  "Rajshahi": [
    "Bagha",
    "Bagmara",
    "Charghat",
    "Durgapur",
    "Godagari",
    "Mohanpur",
    "Paba",
    "Puthia",
    "Rajshahi Sadar",
    "Tanore",
  ],
  "Rangamati": [
    "Bagaichhari",
    "Barkal",
    "Belaichhari",
    "Juraichhari",
    "Kaptai",
    "Kaukhali",
    "Langadu",
    "Nannerchar",
    "Rajasthali",
    "Rangamati Sadar",
  ],
  "Rangpur": [
    "Badarganj",
    "Gangachhara",
    "Kaunia",
    "Mithapukur",
    "Pirgachha",
    "Pirganj",
    "Rangpur Sadar",
    "Taraganj",
  ],
  "Satkhira": [
    "Assasuni",
    "Debhata",
    "Kalaroa",
    "Kaliganj",
    "Satkhira Sadar",
    "Shyamnagar",
    "Tala",
  ],
  "Shariatpur": [
    "Bhedarganj",
    "Damudya",
    "Gosairhat",
    "Naria",
    "Shariatpur Sadar",
    "Zajira",
  ],
  "Sherpur": [
    "Jhenaigati",
    "Nakla",
    "Nalitabari",
    "Sherpur Sadar",
    "Sreebardi",
  ],
  "Sirajganj": [
    "Belkuchi",
    "Chauhali",
    "Kamarkhanda",
    "Kazipur",
    "Raiganj",
    "Shahjadpur",
    "Sirajganj Sadar",
    "Tarash",
    "Ullahpara",
  ],
  "Sunamganj": [
    "Bishwamvarpur",
    "Chhatak",
    "Derai",
    "Dharamapasha",
    "Dowarabazar",
    "Jagannathpur",
    "Jamalganj",
    "Sullah",
    "Sunamganj Sadar",
    "Tahirpur",
  ],
  "Sylhet": [
    "Balaganj",
    "Beanibazar",
    "Bishwanath",
    "Companiganj",
    "Dakshin Surma",
    "Fenchuganj",
    "Golapganj",
    "Gowainghat",
    "Jaintiapur",
    "Kanaighat",
    "Osmani Nagar",
    "Sylhet Sadar",
    "Zakiganj",
  ],
  "Tangail": [
    "Basail",
    "Bhuapur",
    "Delduar",
    "Dhanbari",
    "Ghatail",
    "Gopalpur",
    "Kalihati",
    "Madhupur",
    "Mirzapur",
    "Nagarpur",
    "Sakhipur",
    "Tangail Sadar",
  ],
  "Thakurgaon": [
    "Baliadangi",
    "Haripur",
    "Pirganj",
    "Ranisankail",
    "Thakurgaon Sadar",
  ],
};

export const DISTRICTS = Object.keys(BD_GEO).sort();
